name: Security Code Scan Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scs-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Projenizin kullandığı .NET versiyonuna göre değiştirin

    - name: Install SCS Tool
      run: dotnet tool install --global SecurityCodeScan.Tool

    - name: Run SCS Scan
      run: dotnet scs . --output-format json
